salmonella-epidemy: remove --eggs-source-dir support
chicken-install uses egg-sources-dir to compile and remove egg files,
which can be dangerous when multiple salmonella instances are running
in parallel.

Here's an example of a race condition caused by that (installation log for awful):

-------------------------------8<------------------------------
installing json:1.5 ...
changing current directory to /home/salmonella/salmonella/henrietta/json/tags/1.5
  /home/salmonella/local/chicken-4.8.0.2/bin/csi -bnq -setup-mode -e \
  "(require-library setup-api)" -e "(import setup-api)" -e "(setup-error-handling)" \
  -e "(extension-name-and-version '(\"json\" \"1.5\"))" -e \
  "(destination-prefix \"/home/salmonella/salmonella/epidemy/4/repo\")" \
  -e "(runtime-prefix \"/home/salmonella/salmonella/epidemy/4/repo\")" \
  /home/salmonella/salmonella/henrietta/json/tags/1.5/json.setup
  /home/salmonella/local/chicken-4.8.0.2/bin/csc -feature compiling-extension \
  -setup-mode    json.scm -s -O2 -d1 -j json

Error: (delete-file) cannot delete file - No such file or directory: "json.c"

------------------------------->8------------------------------

This error occured because another salmonella instance was using the
json source directory at the same time.